Swe 7394 update lib
qonsoll/translation pull request #4
Opened 2023-01-26 10:56 UTC by olenashevchuk

2023-01-26 13:07 UTC, Arthur-Pochinok-MENTA requested changes

2023-01-26 13:07 UTC, Arthur-Pochinok-MENTA commented on src/TranslationProvider.js
> +    // Get formatted date and time, in format "2023 1 26 14:21:19"
Please, use date&time format which AI helper suggests
<img width="1592" alt="Screenshot 2023-01-26 at 14 05 34" src="https://user-images.githubusercontent.com/101116443/214842861-ab7644b9-e241-45ad-ba5f-2c4ed73596ed.png">

2023-01-26 19:01 UTC, okrdima approved these changes

2023-03-28 13:11 UTC, VladBogach approved these changes

2023-03-28 13:11 UTC, merged